### ISSUE TITLE
Hi ! I just have few questions on ASPERA & NCBI request upper limit !

### ISSUE THREAD

**Issue by acuacal** [StuntsPT/NCBI_Mass_Downloader#17]
Hi

Thank you so much for making this amazing program !!

I just installed it, but before I use, I just have 2 questions

1. Does this program support ASPERA?

2. Does this program can handle with NCBI guide line on request upper limit? 
(They say "Make no more than 3 requests every 1 second")

Thanks for reading !

**Comment by StuntsPT** [comment]
Hi @acuacal,
Glad to hear you like the program. I hope it's useful for you.
To answer your questions:
1. All downloads are performed via `https` using NCBI's API, so, no ASPERA is not used.
2. NCBI Mass Sequence downloader will conform to the limit of less than 3 requests per second - no need to worry.
If you need further help, just ask away.

**Comment by StuntsPT** [comment]
Closing, since this seems to be solved.
