### ISSUE TITLE
multiple errors linux

### ISSUE THREAD

**Issue by Phylloxera** [StuntsPT/NCBI_Mass_Downloader#19]
Hi, looks like a great tool!

I'm getting this error when attempting to run with python 2.7.14 on a Debian server:
[9613] Error loading Python lib '/tmp/_MEIoM0vlJ/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIoM0vlJ/libpython3.6m.so.1.0)

And this error when attempting using python 3.5.4 on the same server:
  File "dist/NCBI_downloader", line 1
SyntaxError: Non-UTF-8 code starting with '\xe8' in file dist/NCBI_downloader on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I'm getting this error with python 2.7.12 on a Centos server:
dist/NCBI_downloader: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIMUjOc4/libz.so.1)

And this error with python 3.5.2 on the same server:
File "dist/NCBI_downloader", line 1
SyntaxError: Non-UTF-8 code starting with '\xe8' in file dist/NCBI_downloader on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I'll try to build a singularity that has all the necessary LIBs. Let me know what you come up with on these.

Thanks! Aaron

**Comment by StuntsPT** [comment]
Hi @Phylloxera ,
It seems you are trying to run the binaries using `python`.
You only need to use `python` if you are trying to run from the source code directly (in which case you need `python` (both python2 and python3 should work, but python3 is better tested) and `pyqt5` installed).
Typically you would clone the github repository and then use python to run the code. Something like this:

```bash
git clone https://github.com/StuntsPT/NCBI_Mass_Downloader.git
cd NCBI_Mass_Downloader
python3 NCBI_downloader.py
```

Alternatively, you can download the binary from the [releases page](https://github.com/StuntsPT/NCBI_Mass_Downloader/releases/tag/v4.3), uncompress it and run it directly. In this case you do not need to have `pyqt5` or even `python` installed.

```bash
wget https://github.com/StuntsPT/NCBI_Mass_Downloader/releases/download/v4.3/NCBI_Mass_Sequence_Downloader_Linux_x86_64-v4.3.tar.xz
tar xvfJ NCBI_Mass_Sequence_Downloader_Linux_x86_64-v4.3.tar.xz
./NCBI_downloader
```
Let me know if you can run the program with either of these alternatives.

**Comment by Phylloxera** [comment]
Cloning the source worked, thanks! The binaries don't seem to when called on their own with no python prefix. Errors #1 and #3 are still the same.

**Comment by StuntsPT** [comment]
Happy that it's working for you!
The binaries issues could be due to a glibc mismatch.
I'll try to compile an alternative binary with an older glibc and post it here. It would be super if you could try it for me.
Is that works, I'll start building the binaries on a box with an older glibc version.

**Comment by StuntsPT** [comment]
@Phylloxera, would you be so kind as to try this binary on your Debian and CentOS servers?
This was built on a machine running Ubuntu 16.04 (I was unable to build a stable binary using 14.04), which is packaged with an older version of `glibc` than the ArchLinux boxes I have been building it with. It is therefore, more likely to work with your servers.
Thank you in advance.

You can find the testing binary on [this link](https://transfer.sh/UaWPT/NCBI_downloader.gz) (it had to be an external link, since github won't support attaching files with more than 10Mb).

**Comment by Phylloxera** [comment]
This binary works on the newer Debian but not on the older CentOS. 1 of 2 ain't bad and the source works fine on the CentOS. I really like the feature that it verifies receipt of all sequences. I had a 900K sequence DB to compile from a search term. It took a few hours but much better than the curl timing out in my R script and needing to start over! I've been thinking... when I need to update said monster DB, it might be better to somehow just get a list of new accession numbers relative to the old DB rather than downloading the whole thing each time from scratch... Anyway, thanks again!

**Comment by StuntsPT** [comment]
You're welcome. Thank **you** for testing that binary.
Trying to build the binary on my 14.04 machine fails with a lot of strange errors (but it should work with older versions of CentOS).
I guess 16.04 is as far back as I can currently go. But I guess it's still better than building on my current machine. I'll start distributing binaries built like this in the next version.
Yes, this is one of the main use-cases of *NCBI Mass Sequence Downloader*. Doing what you suggest should **really** save a lot of time during downloads.
I'm happy it's working for you.
Feel free to open up any further issues if you find any (or ask any other questions, as for that matter)!
