### ISSUE TITLE
wrong Installation documentation

### ISSUE THREAD

**Issue by renzok** [StuntsPT/NCBI_Mass_Downloader#4]
The Readme says:

> Installation:
>Not required. Just clone the repository or uncompress one of the releases and run from there

This is a contradiction. Every software needs an installation and this is an example of badly written installation instruction:

"Just clone the repository or uncompress one of the releases and run from there"

What about link to documentation on how to clone ot simply example command lines?

What about a link to the recent release?

**Comment by StuntsPT** [comment]
Thanks for all the feedback.
The issues #4 #5 and #6 come down to documentation.
I agree, the project has grown enough that a simple README won't do anymore.
I am currently rebuilding all the docs to be hosted on readthedocs.org, which should also facilitate the inclusion of an online manual inside the program itself.
