### ISSUE TITLE
Implement same input parameter check for cli and gui version

### ISSUE THREAD

**Issue by renzok** [StuntsPT/NCBI_Mass_Downloader#9]
In addition to a proper cli it is good to have a common function which checks the input parameters and gives meaningful error messages for non=it-experts in case of wrong input values.

**Comment by StuntsPT** [comment]
Thanks for all the feedback.
The issues you have pointed out have **really** improved the software.

**Comment by renzok** [comment]
you are welcome :)

However, reviewing the [commit](https://github.com/StuntsPT/NCBI_Mass_Downloader/commit/ecc58b6bbcb11212e844cd58783ef45e6948e49f), there is still not a single code base to check the input parameters independent if they come from the GUI or CLI. In addition, there is no way of giving an email address as CLI parameter see #13

**Comment by StuntsPT** [comment]
I like using argparse for the sanity checks (too bad it won't work in the GUI too).
I'll branch the code tonight to try a new module for sanity checks and see how it looks. It may help future maintainability.

**Comment by StuntsPT** [comment]
After working on it for a few hours, I'm giving up on a [common sanity check](https://github.com/StuntsPT/NCBI_Mass_Downloader/tree/common_sanity) which no matter how I twist and turn it is leading to a lot more code duplication, not less.
It's also making to code feel more like spaghetti than what I am comfortable with.
The idea is good in theory, but in practice it's not turning out so well...
